server:
  port: 12000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.146.200:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://ddqmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_service
          uri: lb://ddqmall-third-service
          predicates:
            - Path=/api/thirdservice/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
  # 前端项目，/api
  application:
    name: ddqmall-gateway